export const POST_USER_SIGNUP_REQUEST = "POST_USER_SIGNUP_REQUEST";
export const POST_USER_SIGNUP_SUCCESS = "POST_USER_SIGNUP_SUCCESS";
export const POST_USER_SIGNUP_FAILURE = "POST_USER_SIGNUP_FAILURE";